# Generated by Django 4.2.7 on 2023-11-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kucna_hemija', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barkod', models.CharField(max_length=20, unique=True)),
                ('naziv_proizvoda', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('na_stanju', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
